"""
Runs multiple `ROCCO_chrom.py` jobs, which execute ROCCO (Algorithm 2 in paper)
method on each respective chromosome. Chromosome-specific parameters
are collected in a CSV file specified with argument `-p --param_file`. Consider
using `est_budgets.py` to compute chromosome-specific budgets using read density.

If any parameter entry in the CSV file `--param_file` is set to `NULL`, the script uses the
corresponding default value specified by command-line arguments.

Supports parallel execution of multiple `ROCCO_chrom.py` jobs via `--jobs`.
    If `--jobs` is set to `0`, the script runs the maximum possible jobs in parallel.

    If `--jobs` is set to `1`, the jobs are executed sequentially (default)

    If `--jobs` is `j>1`, `j` jobs are executed in parallel.

The output files generated by `ROCCO_chrom.py` are stored in the specified output
directory (`--outdir`). If the `combine` argument is provided not `None`,then the
script combines the chromosome-specific bed files into a single output file.

Note on `--solver`: The default solver is ECOS, which is free and open-source, and is
installed alongside cvxpy. Though ECOS is a viable option, using the MOSEK solver can
improve speed substantially. Free academic licenses for MOSEK can be obtained instantly
with a valid .edu email address:
https://www.mosek.com/products/academic-licenses/

(Generous free trials are also available for commercial use). After obtaining the
license, create a directory `mosek` in your home directory:

```
mkdir ~/mosek
mv mosek.lic ~/mosek
```

Then, run:

```
pip install mosek
```

After these steps, you should be able to specify MOSEK with
with `--solver MOSEK` when calling ROCCO.py

```
Usage: python ROCCO.py [options]

Options:
-h, --help            show this help message and exit
-p PARAM_FILE, --param_file PARAM_FILE
                    CSV param file with a row for each chromosome
-b BUDGET, --budget BUDGET
                    Set the budget parameter (default: 0.035)
-g GAMMA, --gamma GAMMA
                    Set the gamma parameter (default: 1.0)
-t TAU, --tau TAU     Set the tau parameter (default: 0.0)
--c1 C1               Set the c1 parameter (default: 1.0)
--c2 C2               Set the c2 parameter (default: 1.0)
--c3 C3               Set the c3 parameter (default: 1.0)
-N RR_ITER, --rr_iter RR_ITER
                    Set the number of RR iterations (default: 50)
--solver SOLVER       Set the optimization solver to be used (default: ECOS)
--bed_format BED_FORMAT
                    Specify BED3 or BED6 format (default: 3)
--identifiers IDENTIFIERS
                    File containing sample/replicate identifiers on each line
--outdir OUTDIR       Directory to store ROCCO's output files (default: current directory)
--combine COMBINE     If *not* None, combine output bed files and store in the specified file
-j JOBS, --jobs JOBS  Number of chromosome-specific jobs to run in parallel (default: 1)
-m MEM, --mem MEM     Wait to start a ROCCO_chrom.py job until there is at least MEM memory available
--parlog PARLOG       Log file for GNU Parallel (default: ROCCO_parlog.txt)
--verbose             Enable verbose output
```

Example:
    Run on toy/test data in `tests/data`:
    ```
    python3 ROCCO.py -p tests/test_params.csv --outdir . --combine tests/combined.bed
    ```

Notes:
    - If using computing environment with a workload manager, e.g., SLURM, consider manually
        creating `ROCCO_chrom.py` jobs for each chromosome. This is typically much faster.
"""

import os
import argparse
import subprocess
import tempfile
import rocco_aux


def get_params(param_file: str, budget: float, gamma: float, tau: float,
               c1: float, c2: float, c3: float) -> list:
    """
    Grabs parameters for each chromosome from `param_file`

    This function collects parameters from each chromosome-row of
    `params.csv`. If a `NULL` entry is encountered, it is replaced
    by the CLI-specified default (see `args`).

    Args:
        param_file (str) : a CSV file with a row containing parameter vals\
            to use for each chromosome.

    Returns:
        list: a list of lists, with each element containing
          the necessary parameters to run a `ROCCO_chrom.py` job.
    """
    defaults = [None, None, budget, gamma, tau, c1, c2, c3]
    chrom_params = []
    with open(param_file, mode='r', encoding='utf-8') as par_file:
        header = True
        for line in par_file:
            if header is True:
                header = False
                continue
            if ',' not in line:
                continue
            line = line.strip()
            line = line.split(',')
            for i, entry in enumerate(line):
                if entry == 'NULL':
                    # replace NULL entries with the genome-wide default
                    line[i] = defaults[i]
            chrom_params.append(line)
    return chrom_params


def call_rocco(chrom, wig_path, budget, gamma, tau, c1, c2, c3, solver,
               bed_format, verbose=False, N=50, identifiers=None,
               outdir='.') -> str:
    r"""
    Formats a command to run `ROCCO_chrom.py` for a given chromosome

    Args:
        chrom (str): chromosome name. Example: `chr1`
        wig_path (str): path to the *directory* containing samples' signal
            tracks for `chrom`
        budget (float): budget constraint
        tau (float): tau in $\mathcal{S}(i)$
        gam (float): gamma parameter in $f(\mathbf{\ell})$
        c1 (float): c1 value in $\mathcal{S}(i)$
        c2 (float): c2 value in $\mathcal{S}(i)$
        c3 (float): c3 value in $\mathcal{S}(i)$
        N (int): RR procedure iterations. If N <= 0,
            $\texttt{floor\_eps}$ procedure is applied...
            See `Loci.run_rr()`
        verbose_ (bool): Verbosity flag for the solver
        solver (str): the solver to use--either "ECOS" or "MOSEK"
    Returns:
        str: a formatted ROCCO_chrom.py command with the appropriate parameters.
        substituted.
    """
    cli_args = ["python3", os.getcwd() + '/' + "ROCCO_chrom.py",
                '--chrom', chrom,
                '--wig_path', wig_path,
                '--budget', budget,
                '--gamma', gamma,
                '--tau', tau,
                '--c1', c1,
                '--c2', c2,
                '--c3', c3,
                '--solver', solver,
                '--bed_format', bed_format,
                '--outdir', outdir,
                '--rr_iter', N,
                '--identifiers', identifiers,
                '--verbose']

    if not verbose:
        cli_args.remove('--verbose')
    if identifiers is None:
        cli_args.remove('--identifiers')
        cli_args.remove(identifiers)
    return ' '.join(cli_args)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--param_file',
                        default='params.csv',
                        help="CSV param file w/ row for each chromosome")
    # if some parameters are left `NULL` in `param_file`,
    # the values given by the following arguments will be
    # used as defaults.
    parser.add_argument('-b', '--budget', default=.035)
    parser.add_argument('-g', '--gamma', default=1.0)
    parser.add_argument('-t', '--tau', default=0.0)
    parser.add_argument('--c1', default=1.0)
    parser.add_argument('--c2', default=1.0)
    parser.add_argument('--c3', default=1.0)
    parser.add_argument('-N', '--rr_iter', type=int, default=50)
    parser.add_argument('--solver', default="ECOS",
                        help="Optimization software used to solve the \
                        LP underlying ROCCO. `ECOS` is used by default \
                        and is a viable open-source option. `MOSEK`\
                        offers significantly greater speed and is free\
                        for academic use. Free trial commerical licenses\
                        are also available. See\
                        https://www.mosek.com/products/academic-licenses/")
    parser.add_argument('--bed_format', type=int, default=3,
                        help="Specifies BED3 or BED6 format.\
                        Default is BED6. Generate BED3 output with \
                        --bed_format 3")
    parser.add_argument('--identifiers', default=None,
                        help="an optional filename containing identifiers\
                          for samples to include in experiment. Each identi\
                          fier should be a substring of the `.wig` sample")
    parser.add_argument('--outdir', default='.',
                        help="directory in which to store ROCCO's output\
                          files.")
    parser.add_argument('--combine', default=None, help="if not None, combine\
                        output bed files and store in the file specified\
                        with this parameter. ex: `--combine bedname.bed` con-\
                        catenates the chromosome-specific bedfiles into `bedname.bed`.")
    parser.add_argument('-j', '--jobs', type=int, default=1,
                        help="number of chromosome-specific jobs to run in parallel.\
                            If set to `0`, the maximum possible jobs are created.")
    parser.add_argument('-m', '--mem', default=None,
                        help="if running in parallel, wait to start a ROCCO_chrom.py job\
                            until there is at least `-m` memory avilable. See GNU Parallel's\
                            `--memfree` parameter.")
    parser.add_argument(
        '--parlog',
        default='ROCCO_parlog.txt',
        help='logfile for GNU Parallel')
    parser.add_argument('--verbose', default=False, action="store_true")
    args = vars(parser.parse_args())

    chrom_args = get_params(args['param_file'], args['budget'],
                            args['gamma'], args['tau'], args['c1'],
                            args['c2'], args['c3'])
    if args['jobs'] == 0:
        print("running maximum possible ROCCO_chrom.py jobs in parallel")
    elif args['jobs'] == 1:
        print("running each ROCCO_chrom.py job sequentially")
    else:
        print("running min({}, num. chroms) jobs in parallel".format(
                args['jobs']))
    args['outdir'] = rocco_aux.trim_path(args['outdir'])
    if not os.path.exists(args['outdir']):
        os.mkdir(args['outdir'])

    tmp = tempfile.NamedTemporaryFile(mode="w+")
    for i, arglist in enumerate(chrom_args):
        arglist = [str(x) for x in arglist]
        cmd = call_rocco(arglist[0], arglist[1], arglist[2], arglist[3],
                         arglist[4], arglist[5], arglist[6], arglist[7],
                         args['solver'], str(args['bed_format']),
                         args['verbose'], str(args['rr_iter']),
                         identifiers=args['identifiers'], outdir=args['outdir'])
        print("job {}: {}".format(i, cmd))

        if args['jobs'] == 1:
            seq_process = subprocess.run(cmd.split(' '),
                                         capture_output=True, text=True, check=True)
            print(seq_process.stdout)

        tmp.write(str(cmd + '\n'))

    tmp.flush()
    cmd = ['parallel',
           '-k',
           '--joblog', args['parlog'],
           '--jobs', str(args['jobs']),
           '-a', tmp.name]

    if args['mem'] is not None:
        cmd += ['--memfree', args['mem']]
    if args['jobs'] != 1:
        print(' '.join(cmd))
        with subprocess.Popen(cmd, stdout=subprocess.PIPE, bufsize=1, universal_newlines=True) as par_proc:
            if args['verbose']:
                for line in par_proc.stdout:
                    print(line, end='')
            par_proc.wait()
    tmp.close()

    if args['combine'] is not None:
        print('combining output files --> {}'.format(args['combine']))
        rocco_aux.sort_combine_bed(args['combine'], dir_=args['outdir'])


if __name__ == "__main__":
    main()
