"""
Runs multiple `ROCCO_chrom.py` jobs, which execute ROCCO (Algorithm 2 in paper)
method on each respective chromosome. Chromosome-specific parameters
are collected in a CSV file specified with argument `-p --param_file`. Consider
using `est_budgets.py` to compute chromosome-specific budgets using read density.

If any parameter entry in the CSV file `--param_file` is set to `NULL`, the script uses the
corresponding default value specified by command-line arguments.

Supports simultaneous execution of multiple `ROCCO_chrom.py` jobs via `--multi`. This option can improve speed substantially but uses more peak memory than the default, sequential approach.

The output files generated by `ROCCO_chrom.py` are stored in the specified output
directory (`--outdir`). If the `combine` argument is provided not `None`,then the
script combines the chromosome-specific bed files into a single output file.

Note on `--solver`: The default solver is ECOS, which is free and open-source, and is
installed alongside cvxpy. Though ECOS is a viable option, using the MOSEK solver can
improve speed substantially. Free academic licenses for MOSEK can be obtained instantly
with a valid .edu email address:
https://www.mosek.com/products/academic-licenses/

(Generous free trials are also available for commercial use). After obtaining the
license, create a directory `mosek` in your home directory:

```
mkdir ~/mosek
mv mosek.lic ~/mosek
```

Then, run:

```
pip install mosek
```

After these steps, you should be able to specify MOSEK with
with `--solver MOSEK` when calling ROCCO.py

```
usage: ROCCO.py [-h] [-p PARAM_FILE] [-b BUDGET] [-g GAMMA] [-t TAU] [--c1 C1] [--c2 C2] [--c3 C3] [-N RR_ITER] [--solver SOLVER]
                [--bed_format BED_FORMAT] [--identifiers IDENTIFIERS] [--outdir OUTDIR] [--combine COMBINE] [-j JOBS] [-m MEM]
                [--parlog PARLOG] [--multi] [--verbose]

options:
  -h, --help            show this help message and exit
  -p PARAM_FILE, --param_file PARAM_FILE
                        CSV param file w/ row for each chromosome
  -b BUDGET, --budget BUDGET
  -g GAMMA, --gamma GAMMA
  -t TAU, --tau TAU
  --c1 C1
  --c2 C2
  --c3 C3
  -N RR_ITER, --rr_iter RR_ITER
  --solver SOLVER       Optimization software used to solve the LP underlying ROCCO. `ECOS` is used by default and is a viable
                        open-source option. `MOSEK` offers significantly greater speed and is free for academic use. Free trial
                        commerical licenses are also available. See https://www.mosek.com/products/academic-licenses/
  --bed_format BED_FORMAT
                        Specifies BED3 or BED6 format. Default is BED6. Generate BED3 output with --bed_format 3
  --identifiers IDENTIFIERS
                        an optional filename containing identifiers for samples to include in experiment. Each identi fier should
                        be a substring of the `.wig` sample
  --outdir OUTDIR       directory in which to store ROCCO's output files.
  --combine COMBINE     if not None, combine output bed files and store in the file specified with this parameter. ex: `--combine
                        bedname.bed` con- catenates the chromosome-specific bedfiles into `bedname.bed`.
  -j JOBS, --jobs JOBS  deprecated: included for backwards compatibility. use `--multi` instead.
  -m MEM, --mem MEM     deprecated: included for backwards compatibility. use `--multi` instead.
  --parlog PARLOG       deprecated: included for backwards compatibility. use `--multi` instead.
  --multi               run ROCCO_chrom.py jobs simultaneously to improve speed. increases peak memory expense.
  --verbose
```

Example:
    Run on toy/test data in `tests/data`:
    ```
    python3 ROCCO.py -p tests/test_params.csv --outdir . --combine tests/combined.bed
    ```
"""

import os
import argparse
import subprocess
import tempfile
import rocco_aux


def get_params(param_file: str, budget: float, gamma: float, tau: float,
               c1: float, c2: float, c3: float) -> list:
    """
    Grabs parameters for each chromosome from `param_file`

    This function collects parameters from each chromosome-row of
    `params.csv`. If a `NULL` entry is encountered, it is replaced
    by the CLI-specified default (see `args`).

    Args:
        param_file (str) : a CSV file with a row containing parameter vals\
            to use for each chromosome.

    Returns:
        list: a list of lists, with each element containing
          the necessary parameters to run a `ROCCO_chrom.py` job.
    """
    defaults = [None, None, budget, gamma, tau, c1, c2, c3]
    chrom_params = []
    with open(param_file, mode='r', encoding='utf-8') as par_file:
        header = True
        for line in par_file:
            if header is True:
                header = False
                continue
            if ',' not in line:
                continue
            line = line.strip()
            line = line.split(',')
            for i, entry in enumerate(line):
                if entry == 'NULL':
                    # replace NULL entries with the genome-wide default
                    line[i] = defaults[i]
            chrom_params.append(line)
    return chrom_params


def call_rocco(chrom, wig_path, budget, gamma, tau, c1, c2, c3, solver,
               bed_format, verbose=False, N=50, identifiers=None,
               outdir='.') -> str:
    r"""
    Formats a command to run `ROCCO_chrom.py` for a given chromosome

    Args:
        chrom (str): chromosome name. Example: `chr1`
        wig_path (str): path to the *directory* containing samples' signal
            tracks for `chrom`
        budget (float): budget constraint
        tau (float): tau in $\mathcal{S}(i)$
        gam (float): gamma parameter in $f(\mathbf{\ell})$
        c1 (float): c1 value in $\mathcal{S}(i)$
        c2 (float): c2 value in $\mathcal{S}(i)$
        c3 (float): c3 value in $\mathcal{S}(i)$
        N (int): RR procedure iterations. If N <= 0,
            $\texttt{floor\_eps}$ procedure is applied...
            See `Loci.run_rr()`
        verbose_ (bool): Verbosity flag for the solver
        solver (str): the solver to use--either "ECOS" or "MOSEK"
    Returns:
        str: a formatted ROCCO_chrom.py command with the appropriate parameters.
        substituted.
    """
    cli_args = ["python3", os.getcwd() + '/' + "ROCCO_chrom.py",
                '--chrom', chrom,
                '--wig_path', wig_path,
                '--budget', budget,
                '--gamma', gamma,
                '--tau', tau,
                '--c1', c1,
                '--c2', c2,
                '--c3', c3,
                '--solver', solver,
                '--bed_format', bed_format,
                '--outdir', outdir,
                '--rr_iter', N,
                '--identifiers', identifiers,
                '--verbose']

    if not verbose:
        cli_args.remove('--verbose')
    if identifiers is None:
        cli_args.remove('--identifiers')
        cli_args.remove(identifiers)
    return ' '.join(cli_args)

def main(args):
    chrom_args = get_params(args['param_file'], args['budget'],
                            args['gamma'], args['tau'], args['c1'],
                            args['c2'], args['c3'])

    args['outdir'] = rocco_aux.trim_path(args['outdir'])
    if not os.path.exists(args['outdir']):
        os.mkdir(args['outdir'])

    tmp = tempfile.NamedTemporaryFile(mode="w+")
    for i, arglist in enumerate(chrom_args):
        arglist = [str(x) for x in arglist]
        cmd = call_rocco(arglist[0], arglist[1], arglist[2], arglist[3],
                         arglist[4], arglist[5], arglist[6], arglist[7],
                         args['solver'], str(args['bed_format']),
                         args['verbose'], str(args['rr_iter']),
                         identifiers=args['identifiers'], outdir=args['outdir'])
        if not args['multi']:
            try:
                seq_process = subprocess.run(cmd.split(' '),
                                         capture_output=True, text=True, check=True)
                print(seq_process.stdout)
            except Exception as ex:
                print(ex)
                print(seq_process.stderr)
                raise ex
        tmp.write(str(cmd + '\n'))

    tmp.flush()
    if args['multi']:
        rocco_aux.run_par(tmp.name, verbose=args['verbose'])
    tmp.close()

    if args['combine'] is not None:
        print('combining output files --> {}'.format(args['combine']))
        rocco_aux.sort_combine_bed(args['combine'], dir_=args['outdir'])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--param_file',
                        default='params.csv',
                        help="CSV param file w/ row for each chromosome")
    # if some parameters are left `NULL` in `param_file`,
    # the values given by the following arguments will be
    # used as defaults.
    parser.add_argument('-b', '--budget', default=.035)
    parser.add_argument('-g', '--gamma', default=1.0)
    parser.add_argument('-t', '--tau', default=0.0)
    parser.add_argument('--c1', default=1.0)
    parser.add_argument('--c2', default=1.0)
    parser.add_argument('--c3', default=1.0)
    parser.add_argument('-N', '--rr_iter', type=int, default=50)
    parser.add_argument('--solver', default="ECOS",
                        help="Optimization software used to solve the \
                        LP underlying ROCCO. `ECOS` is used by default \
                        and is a viable open-source option. `MOSEK`\
                        offers significantly greater speed and is free\
                        for academic use. Free trial commerical licenses\
                        are also available. See\
                        https://www.mosek.com/products/academic-licenses/")
    parser.add_argument('--bed_format', type=int, default=3,
                        help="Specifies BED3 or BED6 format.\
                        Default is BED6. Generate BED3 output with \
                        --bed_format 3")
    parser.add_argument('--identifiers', default=None,
                        help="an optional filename containing identifiers\
                          for samples to include in experiment. Each identi\
                          fier should be a substring of the `.wig` sample")
    parser.add_argument('--outdir', default='.',
                        help="directory in which to store ROCCO's output\
                          files.")
    parser.add_argument('--combine', default=None, help="if not None, combine\
                        output bed files and store in the file specified\
                        with this parameter. ex: `--combine bedname.bed` con-\
                        catenates the chromosome-specific bedfiles into `bedname.bed`.")
    parser.add_argument('-j', '--jobs', type=int, default=1,
                        help="deprecated: included for backwards compatibility. use `--multi` instead.")
    parser.add_argument('-m', '--mem', default=None,
                        help="deprecated: included for backwards compatibility. use `--multi` instead.")
    parser.add_argument(
        '--parlog',
        default='ROCCO_parlog.txt',
        help='deprecated: included for backwards compatibility. use `--multi` instead.')
    parser.add_argument('--multi', default=False, action='store_true', help='run ROCCO_chrom.py jobs\
        simultaneously to improve speed. increases peak memory expense.')
    parser.add_argument('--verbose', default=False, action="store_true")
    args = vars(parser.parse_args())
    main(args)
