name: API

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install --upgrade pip
      - run: pip install numpy
      - run: pip install scipy==1.10.0
      - run: pip install cvxpy
      - run: pip install sphinx myst_parser
      - run: pip install pandas
      - run: pip install pybedtools
      - run: pip install pyBigWig
      - run: pip install pysam
      - run: sudo apt-get install -y bedtools
      - run: sudo apt-get install -y samtools
      - run: sphinx-build docs docs/build_
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
