name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install numpy
      - run: pip install scipy
      - run: pip install cvxpy
      - run: pip install pandas
      - run: pip install pararead
      - run: pip install logmuse
      - run: pip install pysam
      - run: pip install pybedtools
      - run: pip install pdoc
      - run: sudo apt-get install -y bedtools
      - run: sudo apt-get install -y samtools
      # build documentation into pdocs/
      #
      - run: pdoc locus.py loci.py ROCCO_chrom.py ROCCO.py rocco_aux.py count_matrix.py test_budgets.py prep_bams.py --math -d google -o pdocs/ --logo "https://user-images.githubusercontent.com/57746191/240662475-170478f1-5820-4056-b315-3c8dee3603d9.png"
      - uses: actions/upload-pages-artifact@v1
        with:
          path: pdocs/

  #
  #
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
