name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install numpy
      - run: pip install scipy
      - run: pip install cvxpy
      - run: pip install pandas
      - run: pip install pararead
      - run: pip install logmuse
      - run: pip install pysam
      - run: pip install pybedtools
      - run: sudo apt-get install -y bedtools
      - run: sudo apt-get install -y samtools
      # ADJUST THIS: build your documentation into docs/.
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: pdoc loci.py rocco_aux.py locus.py ROCCO_chrom.py ROCCO.py prep_bams.py --math -d google -o pdocs/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: pdocs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2