name: API

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
      - cli
    paths:
      - '**.py'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install --upgrade pip
      - run: pip install numpy
      - run: pip install scipy==1.10.0
      - run: pip install cvxpy
      - run: pip install pandas
      - run: pip install pararead
      - run: pip install logmuse
      - run: pip install pysam
      - run: pip install pybedtools
      - run: pip install pdoc
      - run: sudo apt-get install -y bedtools
      - run: sudo apt-get install -y samtools
      - run: pdoc rocco/locus.py rocco/loci.py rocco/ROCCO_chrom.py rocco/ROCCO_gwide.py rocco/rocco_aux.py rocco/count_matrix.py rocco/est_budgets.py rocco/prep_bams.py rocco/rocco.py --math -d google -o docs/ --logo "https://user-images.githubusercontent.com/57746191/240662475-170478f1-5820-4056-b315-3c8dee3603d9.png"
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
