name: Tests

on:
  push:
    paths:
      - '**.py'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
        sudo apt-get install -y bedtools
        sudo apt-get install -y samtools
        pip install wheel
        python setup.py sdist bdist_wheel
        pip install -e .

    - name: run test_rocco.py
      working-directory: ./tests
      run: |
        pytest -v -rA test_rocco.py
