name: Tests

on:
  push:
    paths:
      - '**.py'
      - '**.yml'
    branches:
      - main
      - cli
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        sudo apt-get install -y bedtools
        sudo apt-get install -y samtools
        pip install -e .

    - name: run test_rocco.py
      working-directory: ./tests
      run: |
        python test_rocco.py

